- name: show split arn list
  debug:
    msg: "{{ item }}"
  with_items: "{{ role_arn | split(',') | flatten }}"

- name: update ap policy json file inside
  include_tasks: update-policy.yaml
  loop: "{{ ap_policy_only | community.general.json_query('Statement[*].Principal.AWS') }}"
  loop_control:
    index_var: index
    loop_var: loop_items

- name: update bucket policy multi-list
  command: aws s3control put-access-point-policy --account-id {{ account_id }} --name {{ ap_name }}  --policy file://temp-ap-policy.json
